development:
  adapter: mysql
  database: folksemantic_development
  username: root
  password:
  host: localhost
  encoding: utf8
test:
  adapter: mysql
  database: folksemantic_test
  username: root
  password:
  host: localhost
  encoding: utf8
