default: &DEFAULT

  # Sent in emails to users
  application_name: 'Folksemantic'
  from_email: 'support@folksemantic.com'  # Emails will come from this address
  from_email_name: 'Folksemantic'         # This will show up as the name on emails.  i.e. support@example.com <Example>
  support_email: 'support@folksemantic.com'
  admin_email: 'admin@folksemantic.com'
  customer_service_number: '1-800-'

  require_access_code: false              # Determines whether or not an access code is required to sign up.  This can be used for a beta or restricted access sites.

  # Email charset
  mail_charset: 'utf-8'

  # Email server configuration
  # email_server_address: 'mail.topicportal.com'
  # email_user_name: 'support@topicportal.com'
  # email_password: 'engine005'
  # base_domain: 'folksemantic.com'
  email_server_address: "smtp.sendgrid.net"
  email_user_name: 'system@folksemantic.com'
  email_password: 'engine005'
  base_domain: 'folksemantic.com'

  # sign up options
  automatically_activate: true
  automatically_login_after_account_create: true
  send_welcome: true

  # if you use recaptcha you will need to also provide a public and private
  # key available from http://recaptcha.net.
  use_recaptcha: false
  recaptcha_pub_key: GET_A_RECAPTCHA_KEY(TODO)
  recaptcha_priv_key: GET_A_RECAPTCHA_KEY(TODO)

  # jgrowl related settings
  growl_enabled: false

  # application configuration
  let_users_delete_their_account: false  # turn on/off ability for users to delete their own account

  # activity configuration
  enable_live_activity_updates: true # Turns on polling inside the user's activity feed so they constantly get updates from the site
  live_activity_update_interval: 60 # time between updates to live activity feed in seconds
  enable_activity_comments: true    # Turn on comments in the activity feed
  enable_activity_file_uploads: true # Turn on file uploads in the activity feed.  Requires that uploader be installed.
  enable_activity_image_uploads: true # Turn on image uploads in the activity feed.  Requires that uploader be installed.
  enable_activity_video_sharing: true # Turn on video sharing in the activity feed.

  #theme configuration
  themes_enabled: true
  use_domain_for_themes: false

  # ssl
  enable_ssl: false

  # keys
  hoptoad_key: '689a8e04f4737fcc097e01a371c1a5ea'

  # Google analtyics configuration
  google_tracking_code: "UA-9685460-1"
  google_tracking_set_domain: "folksemantic.com"

  # Raker options
  inform_admin_of_global_feed: true
  enable_services_comments: true
  enable_services_shares: true

  amazon_secret_access_key: 'FiO/Xv8+mDAes9KSi+cl9DsRuunOBnawwkCrhMdL'
  amazon_access_key_id: 'AKIAIQNVXNT6WKXFE7IA'
  amazon_associate_tag: 'amzfeeds-20'
  ecs_to_rss_wishlist: "http://www.folksemantic.com/ecs_to_rss-wishlist.xslt"

  google_ajax_api_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRQaNZrEEDRIBVBd1VkQ8sT7SNDLaRQe1aFjcNxFLAP81wDPt61TT_oEDQ'
  request_referer: 'www.folksemantic.com'
  show_google_search: true        # Determines whether or not a google search is displayed on the topic page
  load_feeds_on_server: false     # Determines whether feeds on a topic page are loaded on the server or the client.  Loading on the server can take a while
  combine_feeds_on_server: false  # Combines feeds loaded on the server

  # Geo kit configuration.
  #google_geo_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRTget1rbwn17iEs2m0cvaG6XWvQfxS3Vwresf8QastMRWrJMP4kFpjmlw'
  # TODO make sure the google_ajax_api_key from above can be used with geokit.  If it can then refactor and remove google_geo_key
  # in favor of just using a single key.
  # Get google key from http://www.google.com/apis/maps/signup.html
  google_geo_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRQaNZrEEDRIBVBd1VkQ8sT7SNDLaRQe1aFjcNxFLAP81wDPt61TT_oEDQ'

  # Get yahoo key from http://developer.yahoo.com/maps/rest/V1/geocode.html
  yahoo_geo_key: 'GooreMDV34EbpbHU0CEzWQ.w9RO0fzj_a5WXC1ivotCAlFi1uJHivF6OYZY.NudZ'

  # Oauth
  # Twitter api access: http://www.twitter.com/apps
  twitter_oauth_key: '5vTcRZyHwiw50Przzu2m6w'
  twitter_oauth_secret: '9fwmCGMzn35D3wjxUoE2HX9gutroOrdrBvwnD9oZWw'

  # Google api access: http://code.google.com/apis/accounts/docs/RegistrationForWebAppsAuto.html#register
  google_oauth_key: "www.folksemantic.com"
  google_oauth_secret: "VucT2aBaA8j5LYdzor6AIrfw"

  # Yahoo api access: http://developer.yahoo.com/flickr/
  yahoo_oauth_key: "dj0yJmk9N1dQOTFSM25EeUxpJmQ9WVdrOVYyZGpZa0ppTm04bWNHbzlPREkxTWpNek9EZ3gmcz1jb25zdW1lcnNlY3JldCZ4PTQ0"
  yahoo_oauth_secret: "54b885756a591606b8fcc349ea56cdbe44e919a5"

  # Flick api access: http://www.flickr.com/services/apps/create/apply
  # flickr_oauth_key: b8f7d5395b03a8a3f7b3006bcd7b1435
  # flickr_oauth_secret: 5bd216018e475b02

  # Linked In api access: https://www.linkedin.com/secure/developer
  # linkedin_oauth_key: "Y0D9wmH_aEXb4vO7ZI6sKaT-rnfPAvkG5ogTrCZ2A-0MVzUl6obXQ9w7InfnhHJ0"
  # linkedin_oauth_secret: "yuLlDe2iyIcCZYDOy9NZraEFCyWmp4PbJyuS4AgGhFlsyKGpJ2DSXhQ8ww3kmv6a"
  linkedin_oauth_key: "epsPFmE0UYTXGUBYhXlglRco2381DibCz-Jud3LXlC9Uq7mM8D8bs1PjDjKM_bdj"
  linkedin_oauth_secret: "-BiAFqiL4kTz401gZOiC_AbiV7f_JGgWaPkKgRtZQ01qTloJfSvolMs58fgedP2k"

  # Friendfeed api access: https://friendfeed.com/account/login?next=%2Fapi%2Fregister
  # Production
  friendfeed_oauth_key: '939bcd39423449e89f177a67df5eab52'
  friendfeed_oauth_secret: '4650c80e86e94af689b287df9d2c48c582334c103cb24d1ca3c7cac760d7c5ee'
  # Test
  friendfeed_oauth_key: '0cc48674b6f14ff6bfe185727d00ac46'
  friendfeed_oauth_secret: '7c742d3fe7ae4bb3a4e05014057b04027d29cb2597b84ff9a404ae45b0af236e'

  # Fire Eagle api access: https://fireeagle.yahoo.net/developer/manage
  # fireeagle_oauth_key: 'yCBM3y6OWoZrConsumer'
  # fireeagle_oauth_secret: 'l787ynTBx6QMexqMubqodrHkxfmdCMK8'
  # fireeagle_key: 'ZFF2a5i56iKr'
  # fireeagle_secret: 'y4ln2MHU0Y5VC9McF0f4xYWj9z2M4tdI'

  # Contents
  git_repository: ''
  git_repository: false
  enable_auto_translations: false
  content_enable_solr: true
  content_css: ['/stylesheets/reset.css', '/stylesheets/styles.css']

  # Blogs
  enable_post_activities: true

  # Friend configuration
  enable_following: true
  enable_friending: false
  enable_friend_activity: true

production:
  <<: *DEFAULT
  content_css: ['/stylesheets/all.css']
  # Sent in emails to users
  application_url: 'www.folksemantic.com'

staging:
  <<: *DEFAULT

  # Sent in emails to users
  application_url: 'staging.folksemantic.com'

development:
  <<: *DEFAULT

  application_url: 'localhost:3000'

test:
  <<: *DEFAULT

  # controls account activation and automatic login
  automatically_activate: false
  automatically_login_after_account_create: false

  # turn off for testing
  use_recaptcha: false

  application_url: 'localhost:3000'
