default: &DEFAULT

  email_user_name: 'email@username.com'
  email_password: 'password'

  recaptcha_pub_key: 'GET_A_RECAPTCHA_KEY(TODO)'    # key available from http://recaptcha.net
  recaptcha_priv_key: 'GET_A_RECAPTCHA_KEY(TODO)'

  # keys
  hoptoad_key: '{HOPTOAD key}'

  amazon_secret_access_key: ''
  amazon_access_key_id: ''
  amazon_associate_tag: ''
  ecs_to_rss_wishlist: "http://www.folksemantic.com/ecs_to_rss-wishlist.xslt"

  google_ajax_api_key: ''
  request_referer: 'www.example.com'
  show_google_search: true        # Determines whether or not a google search is displayed on the topic page
  load_feeds_on_server: false     # Determines whether feeds on a topic page are loaded on the server or the client.  Loading on the server can take a while
  combine_feeds_on_server: false  # Combines feeds loaded on the server

  # Geo kit configuration.
  #google_geo_key: ''
  # TODO make sure the google_ajax_api_key from above can be used with geokit.  If it can then refactor and remove google_geo_key
  # in favor of just using a single key.
  # Get google key from http://www.google.com/apis/maps/signup.html
  google_geo_key: ''

  # Get yahoo key from http://developer.yahoo.com/maps/rest/V1/geocode.html
  yahoo_geo_key: ''

  # Oauth
  # Twitter api access: http://www.twitter.com/apps
  twitter_oauth_key: ''
  twitter_oauth_secret: ''

  # Google api access: http://code.google.com/apis/accounts/docs/RegistrationForWebAppsAuto.html#register
  google_oauth_key: "www.example.com"
  google_oauth_secret: ""

  # Yahoo api access: http://developer.yahoo.com/flickr/
  yahoo_oauth_key: ""
  yahoo_oauth_secret: ""

  # Flick api access: http://www.flickr.com/services/apps/create/apply
  # flickr_oauth_key:
  # flickr_oauth_secret:

  # Linked In api access: https://www.linkedin.com/secure/developer
  # linkedin_oauth_key: ""
  # linkedin_oauth_secret: ""
  linkedin_oauth_key: ""
  linkedin_oauth_secret: ""

  # Friendfeed api access: https://friendfeed.com/account/login?next=%2Fapi%2Fregister
  # Production
  friendfeed_oauth_key: ''
  friendfeed_oauth_secret: ''
  # Test
  friendfeed_oauth_key: ''
  friendfeed_oauth_secret: ''

production:
  <<: *DEFAULT
  # Add production specific secrets
staging:
  <<: *DEFAULT
  # Add staging specific secrets
development:
  <<: *DEFAULT
  # Development specific secrets
test:
  <<: *DEFAULT
  # Test specific secrets