default: &DEFAULT

  email_user_name: 'system@folksemantic.com'
  email_password: 'engine005'

  recaptcha_pub_key: 'GET_A_RECAPTCHA_KEY(TODO)'    # key available from http://recaptcha.net
  recaptcha_priv_key: 'GET_A_RECAPTCHA_KEY(TODO)'

  # keys
  hoptoad_key: '689a8e04f4737fcc097e01a371c1a5ea'

  amazon_secret_access_key: 'FiO/Xv8+mDAes9KSi+cl9DsRuunOBnawwkCrhMdL'
  amazon_access_key_id: 'AKIAIQNVXNT6WKXFE7IA'
  amazon_associate_tag: 'amzfeeds-20'
  ecs_to_rss_wishlist: "http://www.folksemantic.com/ecs_to_rss-wishlist.xslt"

  google_ajax_api_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRQaNZrEEDRIBVBd1VkQ8sT7SNDLaRQe1aFjcNxFLAP81wDPt61TT_oEDQ'
  request_referer: 'www.folksemantic.com'
  show_google_search: true        # Determines whether or not a google search is displayed on the topic page
  load_feeds_on_server: false     # Determines whether feeds on a topic page are loaded on the server or the client.  Loading on the server can take a while
  combine_feeds_on_server: false  # Combines feeds loaded on the server

  # Geo kit configuration.
  #google_geo_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRTget1rbwn17iEs2m0cvaG6XWvQfxS3Vwresf8QastMRWrJMP4kFpjmlw'
  # TODO make sure the google_ajax_api_key from above can be used with geokit.  If it can then refactor and remove google_geo_key
  # in favor of just using a single key.
  # Get google key from http://www.google.com/apis/maps/signup.html
  google_geo_key: 'ABQIAAAA7PfG3hsKezJ6slLGywsILRQaNZrEEDRIBVBd1VkQ8sT7SNDLaRQe1aFjcNxFLAP81wDPt61TT_oEDQ'

  # Get yahoo key from http://developer.yahoo.com/maps/rest/V1/geocode.html
  yahoo_geo_key: 'GooreMDV34EbpbHU0CEzWQ.w9RO0fzj_a5WXC1ivotCAlFi1uJHivF6OYZY.NudZ'

  # Oauth
  # Twitter api access: http://www.twitter.com/apps
  twitter_oauth_key: '5vTcRZyHwiw50Przzu2m6w'
  twitter_oauth_secret: '9fwmCGMzn35D3wjxUoE2HX9gutroOrdrBvwnD9oZWw'

  # Google api access: http://code.google.com/apis/accounts/docs/RegistrationForWebAppsAuto.html#register
  google_oauth_key: "www.folksemantic.com"
  google_oauth_secret: "VucT2aBaA8j5LYdzor6AIrfw"

  # Yahoo api access: http://developer.yahoo.com/flickr/
  yahoo_oauth_key: "dj0yJmk9N1dQOTFSM25EeUxpJmQ9WVdrOVYyZGpZa0ppTm04bWNHbzlPREkxTWpNek9EZ3gmcz1jb25zdW1lcnNlY3JldCZ4PTQ0"
  yahoo_oauth_secret: "54b885756a591606b8fcc349ea56cdbe44e919a5"

  # Flick api access: http://www.flickr.com/services/apps/create/apply
  # flickr_oauth_key: b8f7d5395b03a8a3f7b3006bcd7b1435
  # flickr_oauth_secret: 5bd216018e475b02

  # Linked In api access: https://www.linkedin.com/secure/developer
  # linkedin_oauth_key: "Y0D9wmH_aEXb4vO7ZI6sKaT-rnfPAvkG5ogTrCZ2A-0MVzUl6obXQ9w7InfnhHJ0"
  # linkedin_oauth_secret: "yuLlDe2iyIcCZYDOy9NZraEFCyWmp4PbJyuS4AgGhFlsyKGpJ2DSXhQ8ww3kmv6a"
  linkedin_oauth_key: "epsPFmE0UYTXGUBYhXlglRco2381DibCz-Jud3LXlC9Uq7mM8D8bs1PjDjKM_bdj"
  linkedin_oauth_secret: "-BiAFqiL4kTz401gZOiC_AbiV7f_JGgWaPkKgRtZQ01qTloJfSvolMs58fgedP2k"

  # Friendfeed api access: https://friendfeed.com/account/login?next=%2Fapi%2Fregister
  # Production
  friendfeed_oauth_key: '939bcd39423449e89f177a67df5eab52'
  friendfeed_oauth_secret: '4650c80e86e94af689b287df9d2c48c582334c103cb24d1ca3c7cac760d7c5ee'
  # Test
  friendfeed_oauth_key: '0cc48674b6f14ff6bfe185727d00ac46'
  friendfeed_oauth_secret: '7c742d3fe7ae4bb3a4e05014057b04027d29cb2597b84ff9a404ae45b0af236e'

production:
  <<: *DEFAULT
  # Add production specific secrets
staging:
  <<: *DEFAULT
  # Add staging specific secrets
development:
  <<: *DEFAULT
  # Development specific secrets
test:
  <<: *DEFAULT
  # Test specific secrets